### PR TITLE
Maze UK2022f has a missing wall

### PR DESCRIPTION
**Pull request by derekchall**

### CODE REVIEW

**Comment by micromouseonline** [comment]
Thank you for contributing.

Your pull request is really just about the maze error but includes some reverted commits relating to other stuff.

To keep the merge neat and tidy, can you submit only the maze edit as a single commit please? Perhaps squash the individual cimmits into one 

It is also helpful if pull requests always have a description of what they are intended to achieve.

**Comment by derekchall** [comment]
Yes that’s what I was intending to do, only the maze file, I couldn’t find. a way to remove the other stuff, I think I sent only the maze file changes but could not amend the other history.

 [truncated - PH]

**Comment by micromouseonline** [comment]
I will make the edit directly. Perhaps we could schedule a practice session for pull requests if that would help?

**Comment by micromouseonline** [comment]
OK - that is done now. You can just pull down the change.

Thanks again for spotting the error.

**Pull request closed without merging**
